resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource
    
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: https://gitlab.stupidapplications.local/ddieruf/stembuild-concourse.git
    password: 123asd##
    username: ddieruf
    skip_ssl_verification: true
    branch: master

- name: stembuild-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: stembuild
    tag_filter: ((OS_VERSION)).(.*)

- name: lgpo
  type: s3
  source:
    access_key_id: 'minio'
    bucket: stemcell-concourse
    endpoint: http://minio.stupidapplications.local:9000
    secret_access_key: 'minio123'
    regexp: 0.0.(.*)/LGPO.zip

- name: stemcell-store
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    secret_access_key: ((s3.secret_access_key))
    bucket: ((s3.bucket.stemcell))
    endpoint: ((s3.endpoint))
    regexp: bosh-stemcell-(.*)-vsphere.*\.tgz

- name: ubuntu-image
  type: docker-image
  source: { repository: ubuntu }

jobs:
- name: construct
  serial: true
  plan:
    - get: ubuntu-image
    - get: pipeline-tasks
    - get: lgpo
    - get: stembuild-release
      trigger: true
      params:
        globs:
          - stembuild-linux-*
    - task: construct
      file: pipeline-tasks/tasks/construct.yml
      image: ubuntu-image
      input_mapping:
        stembuild: stembuild-release
        lgpo: lgpo
      params:
        vcenter_ca_certs: ((vcenter-ca-certs))
        vcenter_url: ((vcenter-url))
        vcenter_username: ((vcenter-username))
        vcenter_password: ((vcenter-password))
        vm_inventory_path: ((vm-inventory-path))
        vm_ip: ((vm-ip))
        vm_password: ((vm-password))
        vm_username: ((vm-username))

- name: package
  serial: true
  plan:
    - get: ubuntu-image
    - get: pipeline-tasks
    - get: stembuild-release
      passed: [construct]
      params:
        globs:
          - stembuild-linux-*
    - task: construct
      file: pipeline-tasks/tasks/package.yml
      image: ubuntu-image
      input_mapping:
        stembuild: stembuild-release
      params:
        vcenter_ca_certs: ((vcenter-password))
        vcenter_url: ((vcenter-url))
        vcenter_username: ((vcenter-username))
        vcenter_password: ((vcenter-password))
        vm_inventory_path: ((vm-inventory-path))
    - put: stemcell-store
      params:
        file: stemcell/*.tgz